const canManagePharmacy = (user) => ['ADMIN', 'PHARMACIST'].includes(user.role?.slug);
const pharmacyEscape = (value) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
const pharmacyDateTime = (value) => value ? new Date(value).toLocaleString() : '—';
const pharmacySetText = (id, value) => { const element = document.getElementById(id); if (element) element.textContent = value || '—'; };
const pharmacySelect = (select, items, label) => { if (!select) return; select.replaceChildren(select.options[0]); items.forEach((item) => { const option = document.createElement('option'); option.value = item.id; option.textContent = label(item); select.appendChild(option); }); };
const pharmacyShowError = (box, message) => { box.textContent = message; box.classList.remove('hidden'); };

const initialisePharmacyIndex = async (apiRequest, user) => {
    const root = document.getElementById('pharmacyIndexPage');
    if (!root) return;
    const error = document.getElementById('pharmacyError');
    if (!canManagePharmacy(user)) { pharmacyShowError(error, 'Only administrators and pharmacists can access pharmacy operations.'); return; }
    const render = (id, items, label) => {
        const container = document.getElementById(id); container.replaceChildren();
        if (items.length === 0) { container.textContent = 'No alerts.'; return; }
        items.forEach((item) => { const row = document.createElement('div'); row.className = 'rounded-xl bg-slate-50 p-3'; row.innerHTML = `<p class="font-semibold text-slate-900">${pharmacyEscape(label(item))}</p><p class="mt-1 text-xs text-slate-500">${pharmacyEscape(item.batch_number ? `Batch ${item.batch_number} · ${item.expiry_date} · ${item.quantity_available} available` : `${item.stock_total} available · reorder at ${item.reorder_level}`)}</p>`; container.appendChild(row); });
    };
    try { const response = await apiRequest('/pharmacy/alerts'); const data = response.data; pharmacySetText('expiredStockCount', data.expired_count); pharmacySetText('expiringStockCount', data.expiring_count); pharmacySetText('lowStockCount', data.low_stock_count); render('expiredStocks', data.expired, (item) => item.medicine_name); render('expiringStocks', data.expiring, (item) => item.medicine_name); render('lowStockMedicines', data.low_stock, (item) => item.name); } catch (exception) { pharmacyShowError(error, exception.message); }
};

const initialisePharmacyCatalogue = async (apiRequest, user) => {
    const root = document.getElementById('pharmacyCataloguePage');
    if (!root) return;
    const error = document.getElementById('pharmacyCatalogueError');
    if (!canManagePharmacy(user)) { pharmacyShowError(error, 'Only administrators and pharmacists can manage the medicine catalogue.'); return; }
    const categoryForm = document.getElementById('medicineCategoryForm'); const medicineForm = document.getElementById('medicineForm'); const categorySelect = document.getElementById('medicineCategory'); const categoryList = document.getElementById('medicineCategoriesList'); const table = document.getElementById('medicinesTableBody'); const filters = document.getElementById('medicineFilters'); const search = document.getElementById('medicineSearch'); const status = document.getElementById('medicineStatusFilter'); let categories = []; let editingCategory; let editingMedicine;
    const resetCategory = () => { editingCategory = null; categoryForm.reset(); categoryForm.elements.is_active.value = '1'; document.getElementById('categoryFormHeading').textContent = 'Add Category'; document.getElementById('cancelCategoryEdit').classList.add('hidden'); };
    const resetMedicine = () => { editingMedicine = null; medicineForm.reset(); medicineForm.elements.reorder_level.value = '0'; medicineForm.elements.is_active.value = '1'; document.getElementById('medicineFormHeading').textContent = 'Add Medicine'; document.getElementById('medicineSaveButton').textContent = 'Save Medicine'; document.getElementById('cancelMedicineEdit').classList.add('hidden'); };
    const loadCategories = async () => { const response = await apiRequest('/medicine-categories?status=active&per_page=50'); categories = response.data ?? []; pharmacySelect(categorySelect, categories, (item) => item.name); categoryList.replaceChildren(); categories.forEach((category) => { const item = document.createElement('div'); item.className = 'flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm'; item.innerHTML = `<span>${pharmacyEscape(category.name)}</span><div class="flex gap-3"></div>`; const actions = item.querySelector('div'); const edit = document.createElement('button'); edit.type = 'button'; edit.className = 'font-semibold text-cyan-700'; edit.textContent = 'Edit'; edit.addEventListener('click', () => { editingCategory = category.id; categoryForm.elements.name.value = category.name; categoryForm.elements.description.value = category.description ?? ''; categoryForm.elements.is_active.value = category.is_active ? '1' : '0'; document.getElementById('categoryFormHeading').textContent = `Edit ${category.name}`; document.getElementById('cancelCategoryEdit').classList.remove('hidden'); }); actions.append(edit); categoryList.appendChild(item); }); };
    const loadMedicines = async () => { const query = new URLSearchParams({ per_page: '50' }); if (search.value.trim()) query.set('search', search.value.trim()); if (status.value) query.set('status', status.value); const response = await apiRequest(`/medicines?${query}`); table.replaceChildren(); const medicines = response.data ?? []; if (!medicines.length) { table.innerHTML = '<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-slate-500">No medicines found.</td></tr>'; return; } medicines.forEach((medicine) => { const row = document.createElement('tr'); row.className = 'text-sm text-slate-700'; row.innerHTML = `<td class="px-5 py-4"><p class="font-semibold text-slate-900">${pharmacyEscape(medicine.name)}</p><p class="mt-1 text-xs text-slate-500">${pharmacyEscape(medicine.medicine_code)} · ${pharmacyEscape(medicine.generic_name || '')}</p></td><td class="px-5 py-4">${pharmacyEscape(`${medicine.dosage_form} ${medicine.strength || ''}`)}</td><td class="px-5 py-4">${pharmacyEscape(`${medicine.stock_total} / ${medicine.reorder_level}`)}</td><td class="px-5 py-4">${medicine.is_active ? 'Active' : 'Inactive'}</td><td class="px-5 py-4"><div class="flex gap-3"></div></td>`; const actions = row.querySelector('div'); const edit = document.createElement('button'); edit.type = 'button'; edit.className = 'font-semibold text-cyan-700'; edit.textContent = 'Edit'; edit.addEventListener('click', () => { editingMedicine = medicine.id; categorySelect.value = medicine.category?.id ?? ''; medicineForm.elements.name.value = medicine.name; medicineForm.elements.generic_name.value = medicine.generic_name ?? ''; medicineForm.elements.manufacturer.value = medicine.manufacturer ?? ''; medicineForm.elements.dosage_form.value = medicine.dosage_form; medicineForm.elements.strength.value = medicine.strength ?? ''; medicineForm.elements.reorder_level.value = medicine.reorder_level; medicineForm.elements.description.value = medicine.description ?? ''; medicineForm.elements.is_active.value = medicine.is_active ? '1' : '0'; document.getElementById('medicineFormHeading').textContent = `Edit ${medicine.name}`; document.getElementById('medicineSaveButton').textContent = 'Update Medicine'; document.getElementById('cancelMedicineEdit').classList.remove('hidden'); }); const deactivate = document.createElement('button'); deactivate.type = 'button'; deactivate.className = 'font-semibold text-red-600'; deactivate.textContent = 'Deactivate'; deactivate.disabled = !medicine.is_active; deactivate.addEventListener('click', async () => { if (!window.confirm(`Deactivate ${medicine.name}?`)) return; try { await apiRequest(`/medicines/${medicine.id}`, { method: 'DELETE' }); await loadMedicines(); } catch (exception) { pharmacyShowError(error, exception.message); } }); actions.append(edit, deactivate); row.querySelector('td:last-child').append(actions); table.appendChild(row); }); };
    categoryForm.addEventListener('submit', async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(categoryForm).entries()); payload.is_active = payload.is_active === '1'; if (!payload.description) payload.description = null; try { await apiRequest(editingCategory ? `/medicine-categories/${editingCategory}` : '/medicine-categories', { method: editingCategory ? 'PUT' : 'POST', body: JSON.stringify(payload) }); resetCategory(); await loadCategories(); } catch (exception) { pharmacyShowError(error, exception.message); } });
    medicineForm.addEventListener('submit', async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(medicineForm).entries()); payload.medicine_category_id = payload.medicine_category_id ? Number(payload.medicine_category_id) : null; payload.reorder_level = Number(payload.reorder_level); payload.is_active = payload.is_active === '1'; ['generic_name','manufacturer','strength','description'].forEach((key) => { if (!payload[key]) payload[key] = null; }); try { await apiRequest(editingMedicine ? `/medicines/${editingMedicine}` : '/medicines', { method: editingMedicine ? 'PUT' : 'POST', body: JSON.stringify(payload) }); resetMedicine(); await loadMedicines(); } catch (exception) { pharmacyShowError(error, exception.message); } });
    filters.addEventListener('submit', async (event) => { event.preventDefault(); try { await loadMedicines(); } catch (exception) { pharmacyShowError(error, exception.message); } }); document.getElementById('cancelCategoryEdit').addEventListener('click', resetCategory); document.getElementById('cancelMedicineEdit').addEventListener('click', resetMedicine);
    try { await loadCategories(); await loadMedicines(); } catch (exception) { pharmacyShowError(error, exception.message); }
};

const initialisePharmacyStock = async (apiRequest, user) => {
    const root = document.getElementById('pharmacyStockPage'); if (!root) return; const error = document.getElementById('pharmacyStockError'); if (!canManagePharmacy(user)) { pharmacyShowError(error, 'Only administrators and pharmacists can manage stock.'); return; }
    const form = document.getElementById('medicineStockForm'); const medicine = document.getElementById('stockMedicine'); const table = document.getElementById('medicineStocksTableBody'); const filters = document.getElementById('stockFilters'); const search = document.getElementById('stockSearch'); const expiry = document.getElementById('stockExpiryFilter');
    const loadStocks = async () => { const query = new URLSearchParams({ per_page: '50' }); if (search.value.trim()) query.set('search', search.value.trim()); if (expiry.value) query.set('expiry_status', expiry.value); const response = await apiRequest(`/medicine-stocks?${query}`); table.replaceChildren(); const stocks = response.data ?? []; if (!stocks.length) { table.innerHTML = '<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-slate-500">No stock batches found.</td></tr>'; return; } stocks.forEach((stock) => { const row = document.createElement('tr'); row.className = 'text-sm text-slate-700'; row.innerHTML = `<td class="px-5 py-4"><p class="font-semibold text-slate-900">${pharmacyEscape(stock.medicine?.name)}</p><p class="mt-1 text-xs text-slate-500">Batch ${pharmacyEscape(stock.batch_number)}</p></td><td class="px-5 py-4">${pharmacyEscape(stock.quantity_available)}</td><td class="px-5 py-4">${pharmacyEscape(stock.expiry_date)}${stock.expires_soon ? ' (Soon)' : ''}</td><td class="px-5 py-4">${pharmacyEscape(stock.selling_price)}</td><td class="px-5 py-4">${pharmacyEscape(stock.supplier || '—')}</td>`; table.appendChild(row); }); };
    form.elements.received_date.value = new Date().toISOString().slice(0, 10); form.addEventListener('submit', async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(form).entries()); ['medicine_id','quantity_received','unit_cost','selling_price'].forEach((key) => payload[key] = Number(payload[key])); ['supplier','notes'].forEach((key) => { if (!payload[key]) payload[key] = null; }); try { await apiRequest('/medicine-stocks', { method: 'POST', body: JSON.stringify(payload) }); form.reset(); form.elements.received_date.value = new Date().toISOString().slice(0, 10); await loadStocks(); } catch (exception) { pharmacyShowError(error, exception.message); } }); filters.addEventListener('submit', async (event) => { event.preventDefault(); try { await loadStocks(); } catch (exception) { pharmacyShowError(error, exception.message); } });
    try { const response = await apiRequest('/medicines?status=active&per_page=50'); pharmacySelect(medicine, response.data ?? [], (item) => `${item.medicine_code} - ${item.name}`); await loadStocks(); } catch (exception) { pharmacyShowError(error, exception.message); }
};

const initialisePharmacyPrescriptions = async (apiRequest, user) => {
    const root = document.getElementById('pharmacyPrescriptionsPage'); if (!root) return; const error = document.getElementById('pharmacyPrescriptionsError'); if (!canManagePharmacy(user)) { pharmacyShowError(error, 'Only administrators and pharmacists can process prescriptions.'); return; }
    const form = document.getElementById('pharmacyPrescriptionsFilters'); const search = document.getElementById('pharmacyPrescriptionSearch'); const table = document.getElementById('pharmacyPrescriptionsTableBody'); const load = async () => { const query = new URLSearchParams({ per_page: '50' }); if (search.value.trim()) query.set('search', search.value.trim()); const response = await apiRequest(`/pharmacy/prescriptions?${query}`); table.replaceChildren(); const prescriptions = response.data ?? []; if (!prescriptions.length) { table.innerHTML = '<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-slate-500">No prescriptions available.</td></tr>'; return; } prescriptions.forEach((prescription) => { const row = document.createElement('tr'); row.className = 'text-sm text-slate-700'; row.innerHTML = `<td class="px-5 py-4"><p class="font-semibold text-cyan-700">${pharmacyEscape(prescription.prescription_code)}</p><p class="mt-1 text-xs text-slate-500">${pharmacyEscape(pharmacyDateTime(prescription.issued_at))}</p></td><td class="px-5 py-4">${pharmacyEscape(prescription.patient?.full_name)}</td><td class="px-5 py-4">${pharmacyEscape(prescription.doctor?.name)}</td><td class="px-5 py-4">${pharmacyEscape(prescription.dispense_status)}</td><td class="px-5 py-4"><a href="/pharmacy/prescriptions/${prescription.id}" class="font-semibold text-cyan-700">Process</a></td>`; table.appendChild(row); }); }; form.addEventListener('submit', async (event) => { event.preventDefault(); try { await load(); } catch (exception) { pharmacyShowError(error, exception.message); } }); try { await load(); } catch (exception) { pharmacyShowError(error, exception.message); }
};

const initialisePharmacyDispense = async (apiRequest, user) => {
    const root = document.getElementById('pharmacyDispensePage'); if (!root) return; const error = document.getElementById('pharmacyDispenseError'); if (!canManagePharmacy(user)) { pharmacyShowError(error, 'Only administrators and pharmacists can dispense prescriptions.'); return; }
    const prescriptionId = root.dataset.prescriptionId; const form = document.getElementById('prescriptionDispenseForm'); const itemsContainer = document.getElementById('prescriptionDispenseItems'); const history = document.getElementById('dispensingHistory'); let prescription; let medicines = []; let stocks = [];
    const populateBatches = (row, medicineId) => { const batch = row.querySelector('[data-field="batch"]'); batch.replaceChildren(); const blank = document.createElement('option'); blank.value = ''; blank.textContent = medicineId ? 'Select stock batch' : 'Select medicine first'; batch.appendChild(blank); stocks.filter((stock) => String(stock.medicine?.id) === String(medicineId) && !stock.is_expired).forEach((stock) => { const option = document.createElement('option'); option.value = stock.id; option.textContent = `${stock.batch_number} · ${stock.quantity_available} available · expires ${stock.expiry_date}`; batch.appendChild(option); }); };
    const render = () => { pharmacySetText('dispensePrescriptionCode', prescription.prescription_code); pharmacySetText('dispensePatientName', prescription.patient?.full_name); pharmacySetText('dispensePatientAllergies', prescription.patient?.allergies ? `Allergies: ${prescription.patient.allergies}` : 'No known allergies recorded'); pharmacySetText('dispenseDoctor', prescription.doctor?.name); pharmacySetText('dispenseIssuedAt', pharmacyDateTime(prescription.issued_at)); pharmacySetText('dispenseStatus', prescription.dispense_status); itemsContainer.replaceChildren(); prescription.items.forEach((item) => { const row = document.createElement('div'); row.className = 'dispense-item rounded-xl border border-slate-200 p-4'; const quantityHint = item.remaining_quantity !== null ? `Remaining prescribed quantity: ${item.remaining_quantity}` : 'No prescribed quantity recorded; enter the quantity to dispense.'; row.innerHTML = `<div class="mb-4"><p class="font-semibold text-slate-900">${pharmacyEscape(item.medicine_name)}</p><p class="mt-1 text-sm text-slate-500">${pharmacyEscape(`${item.dosage} · ${item.frequency}`)} · ${pharmacyEscape(quantityHint)}</p></div><div class="grid gap-3 md:grid-cols-3"><select data-field="medicine" class="rounded-xl border border-slate-300 px-4 py-3"><option value="">Select matching medicine</option></select><select data-field="batch" required class="rounded-xl border border-slate-300 px-4 py-3"><option value="">Select medicine first</option></select><input data-field="quantity" required type="number" min="0.01" step="0.01" placeholder="Quantity to dispense" class="rounded-xl border border-slate-300 px-4 py-3"></div>`; row.dataset.prescriptionItemId = item.id; const med = row.querySelector('[data-field="medicine"]'); pharmacySelect(med, medicines, (medicine) => `${medicine.medicine_code} - ${medicine.name}`); const match = medicines.find((medicine) => medicine.name.toLowerCase() === item.medicine_name.toLowerCase() || medicine.generic_name?.toLowerCase() === item.medicine_name.toLowerCase()); if (match) { med.value = match.id; populateBatches(row, match.id); } med.addEventListener('change', () => populateBatches(row, med.value)); itemsContainer.appendChild(row); }); history.replaceChildren(); if (!(prescription.dispenses ?? []).length) { history.textContent = 'No dispensing has been recorded.'; } else { prescription.dispenses.forEach((dispense) => { const entry = document.createElement('div'); entry.className = 'rounded-xl bg-slate-50 p-4'; entry.innerHTML = `<p class="font-semibold text-slate-900">${pharmacyEscape(dispense.dispense_code)} · ${pharmacyEscape(dispense.status)}</p><p class="mt-1 text-sm text-slate-500">${pharmacyEscape(pharmacyDateTime(dispense.dispensed_at))} by ${pharmacyEscape(dispense.dispensed_by || '—')}</p>${dispense.notes ? `<p class="mt-2 text-sm text-slate-600">${pharmacyEscape(dispense.notes)}</p>` : ''}`; history.appendChild(entry); }); } };
    const load = async () => { const [prescriptionResponse, medicinesResponse, stocksResponse] = await Promise.all([apiRequest(`/pharmacy/prescriptions/${prescriptionId}`), apiRequest('/medicines?status=active&per_page=50'), apiRequest('/medicine-stocks?per_page=50')]); prescription = prescriptionResponse.data; medicines = medicinesResponse.data ?? []; stocks = stocksResponse.data ?? []; render(); };
    form.addEventListener('submit', async (event) => { event.preventDefault(); const items = [...itemsContainer.querySelectorAll('.dispense-item')].map((row) => ({ prescription_item_id: Number(row.dataset.prescriptionItemId), medicine_stock_id: Number(row.querySelector('[data-field="batch"]').value), quantity_dispensed: Number(row.querySelector('[data-field="quantity"]').value) })).filter((item) => item.medicine_stock_id && item.quantity_dispensed); if (!items.length) { pharmacyShowError(error, 'Select a stock batch and quantity for at least one prescription line.'); return; } try { const response = await apiRequest(`/pharmacy/prescriptions/${prescriptionId}/dispenses`, { method: 'POST', body: JSON.stringify({ notes: form.elements.notes.value || null, items }) }); prescription = response.data; form.elements.notes.value = ''; await load(); } catch (exception) { pharmacyShowError(error, exception.message); } }); try { await load(); } catch (exception) { pharmacyShowError(error, exception.message); }
};

export const initialisePharmacyPages = async (apiRequest, user) => { await initialisePharmacyIndex(apiRequest, user); await initialisePharmacyCatalogue(apiRequest, user); await initialisePharmacyStock(apiRequest, user); await initialisePharmacyPrescriptions(apiRequest, user); await initialisePharmacyDispense(apiRequest, user); };
