@extends('layouts.app')

@section('title', 'Staff | Medora HMS')
@section('page', 'app')
@section('header', 'Staff Management')

@section('content')
<div id="staffIndexPage" class="mx-auto max-w-7xl">
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div><h2 class="text-2xl font-bold text-slate-950">Staff Management</h2><p class="mt-1 text-sm text-slate-500">Maintain employee profiles, daily attendance, and leave decisions.</p></div>
        <div class="flex flex-wrap gap-3"><a href="{{ route('staff.attendance') }}" class="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold hover:bg-slate-50">Attendance</a><a href="{{ route('staff.leave-requests') }}" class="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold hover:bg-slate-50">Leave Requests</a><a href="{{ route('staff.employees.create') }}" class="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white hover:bg-slate-800">+ Add Employee</a></div>
    </div>
    <div id="staffIndexError" class="mb-5 hidden rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"></div>
    <section class="mb-6 grid gap-4 sm:grid-cols-3"><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-slate-500">Active Employees</p><p id="staffActiveCount" class="mt-2 text-3xl font-bold text-slate-950">—</p></article><article class="rounded-2xl border border-cyan-200 bg-cyan-50 p-5 shadow-sm"><p class="text-sm font-medium text-cyan-700">Currently Clocked In</p><p id="staffClockedInCount" class="mt-2 text-3xl font-bold text-cyan-950">—</p></article><article class="rounded-2xl border border-amber-200 bg-amber-50 p-5 shadow-sm"><p class="text-sm font-medium text-amber-700">Pending Leave Requests</p><p id="staffPendingLeaveCount" class="mt-2 text-3xl font-bold text-amber-950">—</p></article></section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><form id="staffEmployeeFilters" class="grid gap-3 border-b border-slate-200 p-5 md:grid-cols-4"><input id="staffEmployeeSearch" type="search" placeholder="Code, name, title, department..." class="rounded-xl border border-slate-300 px-4 py-3"><select id="staffEmployeeStatus" class="rounded-xl border border-slate-300 px-4 py-3"><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="SUSPENDED">Suspended</option><option value="">All statuses</option></select><select id="staffEmployeeDepartment" class="rounded-xl border border-slate-300 px-4 py-3"><option value="">All departments</option></select><button type="submit" class="rounded-xl bg-cyan-600 px-4 py-3 font-semibold text-white hover:bg-cyan-700">Search</button></form><div class="overflow-x-auto"><table class="min-w-full"><thead class="bg-slate-50"><tr class="text-left text-xs font-semibold uppercase tracking-wider text-slate-500"><th class="px-5 py-4">Employee</th><th class="px-5 py-4">Position</th><th class="px-5 py-4">Department</th><th class="px-5 py-4">Joined</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Action</th></tr></thead><tbody id="staffEmployeesTable" class="divide-y divide-slate-100"></tbody></table></div><div class="flex items-center justify-between border-t border-slate-200 px-5 py-4"><p id="staffEmployeesPagination" class="text-sm text-slate-500">Loading...</p><div class="flex gap-2"><button id="staffEmployeesPrev" type="button" class="rounded-lg border border-slate-300 px-4 py-2 text-sm disabled:opacity-40">Previous</button><button id="staffEmployeesNext" type="button" class="rounded-lg border border-slate-300 px-4 py-2 text-sm disabled:opacity-40">Next</button></div></div></section>
</div>
@endsection
