@extends('layouts.app')

@section('title', 'Medicine Catalogue | Medora HMS')
@section('page', 'app')
@section('header', 'Medicine Catalogue')

@section('content')
<div id="pharmacyCataloguePage" class="mx-auto max-w-7xl">
    <div class="mb-6 flex items-center justify-between gap-4"><div><h2 class="text-2xl font-bold text-slate-950">Medicine Catalogue</h2><p class="mt-1 text-sm text-slate-500">Configure medicine categories and active medicines.</p></div><a href="{{ route('pharmacy.index') }}" class="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold">Back to Pharmacy</a></div>
    <div id="pharmacyCatalogueError" class="mb-5 hidden rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"></div>
    <section class="grid gap-6 xl:grid-cols-3">
        <article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex justify-between gap-3"><h3 id="categoryFormHeading" class="font-bold">Add Category</h3><button id="cancelCategoryEdit" type="button" class="hidden text-sm font-semibold text-slate-500">Cancel</button></div><form id="medicineCategoryForm" class="mt-5 space-y-4"><input name="name" required placeholder="Category name" class="w-full rounded-xl border border-slate-300 px-4 py-3"><textarea name="description" rows="3" placeholder="Description (optional)" class="w-full rounded-xl border border-slate-300 px-4 py-3"></textarea><select name="is_active" class="w-full rounded-xl border border-slate-300 px-4 py-3"><option value="1">Active</option><option value="0">Inactive</option></select><button type="submit" class="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Save Category</button></form><div id="medicineCategoriesList" class="mt-6 space-y-2"></div></article>
        <article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-2"><div class="flex justify-between gap-3"><h3 id="medicineFormHeading" class="font-bold">Add Medicine</h3><button id="cancelMedicineEdit" type="button" class="hidden text-sm font-semibold text-slate-500">Cancel</button></div><form id="medicineForm" class="mt-5 grid gap-4 md:grid-cols-2"><select id="medicineCategory" name="medicine_category_id" class="rounded-xl border border-slate-300 px-4 py-3"><option value="">No category</option></select><input name="name" required placeholder="Medicine name" class="rounded-xl border border-slate-300 px-4 py-3"><input name="generic_name" placeholder="Generic name" class="rounded-xl border border-slate-300 px-4 py-3"><input name="manufacturer" placeholder="Manufacturer" class="rounded-xl border border-slate-300 px-4 py-3"><input name="dosage_form" required placeholder="Dosage form (e.g. Tablet)" class="rounded-xl border border-slate-300 px-4 py-3"><input name="strength" placeholder="Strength (e.g. 500 mg)" class="rounded-xl border border-slate-300 px-4 py-3"><input name="reorder_level" required type="number" min="0" step="0.01" value="0" placeholder="Reorder level" class="rounded-xl border border-slate-300 px-4 py-3"><select name="is_active" class="rounded-xl border border-slate-300 px-4 py-3"><option value="1">Active</option><option value="0">Inactive</option></select><textarea name="description" rows="3" placeholder="Description (optional)" class="rounded-xl border border-slate-300 px-4 py-3 md:col-span-2"></textarea><div class="flex justify-end md:col-span-2"><button id="medicineSaveButton" type="submit" class="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Save Medicine</button></div></form></article>
    </section>
    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><form id="medicineFilters" class="grid gap-3 border-b border-slate-200 p-5 md:grid-cols-3"><input id="medicineSearch" type="search" placeholder="Medicine code, name or generic..." class="rounded-xl border border-slate-300 px-4 py-3"><select id="medicineStatusFilter" class="rounded-xl border border-slate-300 px-4 py-3"><option value="active">Active medicines</option><option value="inactive">Inactive medicines</option><option value="">All medicines</option></select><button type="submit" class="rounded-xl bg-cyan-600 px-4 py-3 font-semibold text-white">Search</button></form><div class="overflow-x-auto"><table class="min-w-full"><thead class="bg-slate-50"><tr class="text-left text-xs font-semibold uppercase tracking-wider text-slate-500"><th class="px-5 py-4">Medicine</th><th class="px-5 py-4">Form / Strength</th><th class="px-5 py-4">Stock / Reorder</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Action</th></tr></thead><tbody id="medicinesTableBody" class="divide-y divide-slate-100"></tbody></table></div></section>
</div>
@endsection
